name: ✨ Feature Request
description: Suggest an idea for this project
title: "[FEATURE] "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature 💡  
        Clear explanations help a lot!

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: Describe the problem you are facing.
      placeholder: |
        I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: What would you like to see happen?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: Any alternative solutions or features you've thought about.

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context or screenshots here.

  - type: checkboxes
    id: contribution
    attributes:
      label: Would you like to implement this feature?
      options:
        - label: Yes, I'd like to implement this
        - label: No, but I can help with testing
        - label: No, just suggesting
