#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE_ROOT="$(dirname "$SCRIPT_DIR")"

source "$SCRIPT_DIR/common.sh"

# Check if workspace.yml exists
[[ ! -f "workspace.yml" ]] && error "No workspace.yml found. Run init.sh first."

# Load configuration
load_config "workspace.yml"

log "Syncing workspace components..."

# Get project info
PROJECT_TYPE="${CONFIG_project_type:-book}"
PROJECT_CATEGORY="${CONFIG_project_category:-technical}"
CUSTOM_DIR="${CONFIG_overrides_components_dir:-custom}"

# Create workspace directory
WORKSPACE_DIR="workspace"
ensure_dir "$WORKSPACE_DIR"
ensure_dir "$WORKSPACE_DIR/components"
ensure_dir "$WORKSPACE_DIR/generated"

# Clean previous sync
rm -f "$WORKSPACE_DIR"/preset.tex
rm -rf "$WORKSPACE_DIR"/components/*

log "Project type: $PROJECT_TYPE"
log "Category: $PROJECT_CATEGORY"

# Start building preset.tex
{
    echo "% Auto-generated by Papyrxis workspace sync"
    echo "% DO NOT EDIT - This file is regenerated on each build"
    echo "% Edit workspace.yml to configure components"
    echo ""
    echo "% Generated: $(date)"
    echo ""
} > "$WORKSPACE_DIR/preset.tex"

# Function to add component
add_component() {
    local component="$1"
    local component_path="$WORKSPACE_ROOT/common/components/${component}.tex"
    
    # Check for override
    local override_path="$CUSTOM_DIR/${component}.tex"
    if [[ -f "$override_path" ]]; then
        log "  → Using override: $component"
        cp "$override_path" "$WORKSPACE_DIR/components/${component}.tex"
        echo "\\input{workspace/components/${component}}" >> "$WORKSPACE_DIR/preset.tex"
        return
    fi
    
    # Check if component exists
    if [[ ! -f "$component_path" ]]; then
        warn "Component not found: $component (skipping)"
        return
    fi
    
    log "  → Adding component: $component"
    
    # Copy to workspace directory
    local target_dir="$WORKSPACE_DIR/components/$(dirname "$component")"
    ensure_dir "$target_dir"
    cp "$component_path" "$WORKSPACE_DIR/components/${component}.tex"
    
    # Add to preset.tex
    echo "\\input{workspace/components/${component}}" >> "$WORKSPACE_DIR/preset.tex"
}

# Function to add package group
add_package() {
    local package="$1"
    local package_path="$WORKSPACE_ROOT/common/packages/${package}.tex"
    
    if [[ ! -f "$package_path" ]]; then
        warn "Package not found: $package (skipping)"
        return
    fi
    
    log "  → Adding package: $package"
    cp "$package_path" "$WORKSPACE_DIR/components/${package}.tex"
    echo "\\input{workspace/components/${package}}" >> "$WORKSPACE_DIR/preset.tex"
}

# Get components list
COMPONENTS="${CONFIG_components:-}"

if [[ -z "$COMPONENTS" ]]; then
    # Use preset defaults if no components specified
    log "Using default component set for $PROJECT_CATEGORY $PROJECT_TYPE"
    
    if [[ "$PROJECT_TYPE" == "book" ]]; then
        COMPONENTS="encoding fonts math graphics tables hyperref colors layout titles pagestyles env index bibliography code boxes commands/base"
    else
        COMPONENTS="encoding fonts math graphics tables hyperref colors layout bibliography code commands/base"
    fi
fi

# Add components
for component in $COMPONENTS; do
    # Check if it's a package or component
    if [[ -f "$WORKSPACE_ROOT/common/packages/${component}.tex" ]]; then
        add_package "$component"
    else
        add_component "$component"
    fi
done

# Apply color scheme
COLOR_SCHEME="${CONFIG_colors_scheme:-$PROJECT_CATEGORY}"
log "Applying color scheme: $COLOR_SCHEME"

# Check for custom colors override
if [[ -f "$CUSTOM_DIR/colors.tex" ]]; then
    log "  → Using custom colors"
else
    {
        echo ""
        echo "% Color scheme: $COLOR_SCHEME"
        echo "\\applyColorScheme{$COLOR_SCHEME}"
    } >> "$WORKSPACE_DIR/preset.tex"
fi

# Generate frontmatter for books
if [[ "$PROJECT_TYPE" == "book" ]]; then
    FRONTMATTER="${CONFIG_frontmatter:-}"
    
    if [[ -n "$FRONTMATTER" ]]; then
        log "Generating frontmatter..."
        
        for item in $FRONTMATTER; do
            case "$item" in
                cover)
                    # Generate or copy cover
                    local cover_type="${CONFIG_cover_type:-generated}"
                    
                    if [[ "$cover_type" == "pdf" ]]; then
                        local pdf_file="${CONFIG_cover_pdf_file:-cover.pdf}"
                        if [[ -f "$pdf_file" ]]; then
                            log "  → Using PDF cover: $pdf_file"
                        else
                            warn "PDF cover not found: $pdf_file"
                        fi
                    elif [[ "$cover_type" == "generated" ]]; then
                        log "  → Generating cover page"
                        bash "$WORKSPACE_ROOT/scripts/generate/gen-cover.sh" "workspace.yml"
                    fi
                    ;;
                    
                copyright)
                    log "  → Generating copyright page"
                    bash "$WORKSPACE_ROOT/scripts/generate/gen-copyright.sh" "workspace.yml"
                    ;;
                    
                title)
                    # Check for custom title page
                    if [[ -f "$CUSTOM_DIR/frontmatter/title.tex" ]]; then
                        log "  → Using custom title page"
                        ensure_dir "frontmatter"
                        cp "$CUSTOM_DIR/frontmatter/title.tex" "frontmatter/title.tex"
                    elif [[ -f "$WORKSPACE_ROOT/common/frontmatter/title.tex" ]]; then
                        log "  → Using default title page"
                        ensure_dir "frontmatter"
                        cp "$WORKSPACE_ROOT/common/frontmatter/title.tex" "frontmatter/title.tex"
                    fi
                    ;;
                    
                *)
                    # Copy other frontmatter
                    local fm_file="$WORKSPACE_ROOT/common/frontmatter/${item}.tex"
                    local custom_fm="$CUSTOM_DIR/frontmatter/${item}.tex"
                    
                    if [[ -f "$custom_fm" ]]; then
                        log "  → Using custom $item"
                        ensure_dir "frontmatter"
                        cp "$custom_fm" "frontmatter/${item}.tex"
                    elif [[ -f "$fm_file" ]]; then
                        log "  → Adding frontmatter: $item"
                        ensure_dir "frontmatter"
                        cp "$fm_file" "frontmatter/${item}.tex"
                    fi
                    ;;
            esac
        done
    fi
fi

# Update hyperref with metadata
{
    echo ""
    echo "% Metadata"
    echo "\\hypersetup{"
    echo "  pdftitle={${CONFIG_project_title:-Untitled}},"
    echo "  pdfauthor={${CONFIG_project_author:-Author}},"
    echo "  pdfsubject={${CONFIG_project_subject:-}},"
    echo "  pdfkeywords={${CONFIG_project_keywords:-}},"
    echo "  colorlinks=true,"
    
    if [[ "$PROJECT_CATEGORY" == "academic" ]]; then
        echo "  linkcolor=black,"
        echo "  citecolor=black,"
        echo "  urlcolor=blue"
    else
        echo "  linkcolor=accent,"
        echo "  citecolor=accent,"
        echo "  urlcolor=accent"
    fi
    
    echo "}"
} >> "$WORKSPACE_DIR/preset.tex"

# Generate version command
VERSION=$(get_version)
BUILD_DATE=$(get_build_date)

{
    echo ""
    echo "% Version information"
    echo "\\newcommand{\\ProjectVersion}{$VERSION}"
    echo "\\newcommand{\\BuildDate}{$BUILD_DATE}"
} >> "$WORKSPACE_DIR/preset.tex"

log "Sync completed successfully!"
info "Generated: workspace/preset.tex"
info "Version: $VERSION"
info "Build date: $BUILD_DATE"