#!/usr/bin/env bash
# Sync workspace components based on workspace.yml configuration

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE_ROOT="$(dirname "$SCRIPT_DIR")"

source "$SCRIPT_DIR/common.sh"

# Check if workspace.yml exists
[[ ! -f "workspace.yml" ]] && error "No workspace.yml found. Run init.sh first."

# Load configuration
load_config "workspace.yml"

log "Syncing workspace components..."

# Get project info
PROJECT_TYPE="${CONFIG_project_type:-book}"
PROJECT_CATEGORY="${CONFIG_project_category:-technical}"
CUSTOM_DIR="${CONFIG_overrides_components_dir:-configs}"

# Create workspace directory
WORKSPACE_DIR=".pxis"
ensure_dir "$WORKSPACE_DIR"
ensure_dir "$WORKSPACE_DIR/components"
ensure_dir "$WORKSPACE_DIR/generated"

# Clean previous sync
rm -f "$WORKSPACE_DIR"/preset.tex
rm -rf "$WORKSPACE_DIR"/components/*

log "Project type: $PROJECT_TYPE"
log "Category: $PROJECT_CATEGORY"
log "Override directory: $CUSTOM_DIR"

# Start building preset.tex
{
    echo "% Auto-generated by Papyrxis workspace sync"
    echo "% DO NOT EDIT - This file is regenerated on each build"
    echo "% Edit workspace.yml to configure components"
    echo ""
    echo "% Generated: $(date)"
    echo ""
} > "$WORKSPACE_DIR/preset.tex"

# Function to add component
add_component() {
    local component="$1"
    local component_path="$WORKSPACE_ROOT/common/components/${component}.tex"
    
    # Check for override first
    local override_path="$CUSTOM_DIR/${component}.tex"
    if [[ -f "$override_path" ]]; then
        # Check if override is allowed
        local allowed="${CONFIG_overrides_allow:-}"
        local component_file="${component}.tex"
        
        if [[ " $allowed " == *" $component_file "* ]]; then
            log "  → Using override: $component"
            cp "$override_path" "$WORKSPACE_DIR/components/${component}.tex"
            echo "\\input{$WORKSPACE_DIR/components/${component}}" >> "$WORKSPACE_DIR/preset.tex"
            return
        else
            warn "Override found but not allowed in config: $component"
        fi
    fi
    
    # Check if component exists in workspace
    if [[ ! -f "$component_path" ]]; then
        warn "Component not found: $component (skipping)"
        return
    fi
    
    log "  → Adding component: $component"
    
    # Copy to workspace directory
    local target_dir="$WORKSPACE_DIR/components/$(dirname "$component")"
    ensure_dir "$target_dir"
    cp "$component_path" "$WORKSPACE_DIR/components/${component}.tex"
    
    # Add to preset.tex
    echo "\\input{$WORKSPACE_DIR/components/${component}}" >> "$WORKSPACE_DIR/preset.tex"
}

# Function to add package group
add_package() {
    local package="$1"
    local package_path="$WORKSPACE_ROOT/common/packages/${package}.tex"
    
    if [[ ! -f "$package_path" ]]; then
        warn "Package not found: $package (skipping)"
        return
    fi
    
    log "  → Adding package: $package"
    cp "$package_path" "$WORKSPACE_DIR/components/${package}.tex"
    echo "\\input{$WORKSPACE_DIR/components/${package}}" >> "$WORKSPACE_DIR/preset.tex"
}

# Get components list
COMPONENTS="${CONFIG_components:-}"

if [[ -z "$COMPONENTS" ]]; then
    # Use preset defaults if no components specified
    log "Using default component set for $PROJECT_CATEGORY $PROJECT_TYPE"
    
    if [[ "$PROJECT_TYPE" == "book" ]]; then
        COMPONENTS="fonts math graphics tables hyperref colors layout titles pagestyles env index bibliography code boxes commands/base"
    else
        COMPONENTS="fonts math graphics tables hyperref colors layout bibliography code commands/base"
    fi
fi

# Add components
log "Adding components..."
for component in $COMPONENTS; do
    # Check if it's a package or component
    if [[ -f "$WORKSPACE_ROOT/common/packages/${component}.tex" ]]; then
        add_package "$component"
    else
        add_component "$component"
    fi
done

# Apply color scheme
COLOR_SCHEME="${CONFIG_colors_scheme:-$PROJECT_CATEGORY}"
log "Applying color scheme: $COLOR_SCHEME"

# Check for custom colors override
if [[ -f "$CUSTOM_DIR/colors.tex" ]]; then
    local allowed="${CONFIG_overrides_allow:-}"
    if [[ " $allowed " == *" colors.tex "* ]]; then
        log "  → Using custom colors"
    else
        {
            echo ""
            echo "% Color scheme: $COLOR_SCHEME"
            echo "\\applyColorScheme{$COLOR_SCHEME}"
        } >> "$WORKSPACE_DIR/preset.tex"
    fi
else
    {
        echo ""
        echo "% Color scheme: $COLOR_SCHEME"
        echo "\\applyColorScheme{$COLOR_SCHEME}"
    } >> "$WORKSPACE_DIR/preset.tex"
fi

# Generate frontmatter for books
if [[ "$PROJECT_TYPE" == "book" ]]; then
    FRONTMATTER="${CONFIG_frontmatter:-}"
    
    if [[ -n "$FRONTMATTER" ]]; then
        log "Generating frontmatter..."
        
        for item in $FRONTMATTER; do
            case "$item" in
                cover)
                    cover_type="${CONFIG_cover_type:-generated}"
                    
                    if [[ "$cover_type" == "pdf" ]]; then
                        local pdf_file="${CONFIG_cover_pdf_file:-cover.pdf}"
                        if [[ -f "$pdf_file" ]]; then
                            log "  → Using PDF cover: $pdf_file"
                        else
                            warn "PDF cover not found: $pdf_file"
                        fi
                    elif [[ "$cover_type" == "generated" ]]; then
                        log "  → Generating cover page"
                        bash "$WORKSPACE_ROOT/scripts/generator/cover.sh" "workspace.yml"
                    fi
                    ;;
                    
                copyright)
                    log "  → Generating copyright page"
                    bash "$WORKSPACE_ROOT/scripts/generator/copyright.sh" "workspace.yml"
                    ;;
                    
                title)
                    # Check for custom title page
                    custom_title="$CUSTOM_DIR/frontmatter/title.tex"
                    allowed="${CONFIG_overrides_allow:-}"
                    
                    if [[ -f "$custom_title" ]] && [[ " $allowed " == *" frontmatter/title.tex "* ]]; then
                        log "  → Using custom title page"
                        ensure_dir "frontmatter"
                        cp "$custom_title" "frontmatter/title.tex"
                    elif [[ -f "$WORKSPACE_ROOT/common/frontmatter/title.tex" ]]; then
                        log "  → Using default title page (with substitution)"
                        ensure_dir "frontmatter"
                        
                        # Substitute variables in title page
                        title="${CONFIG_project_title:-Untitled}"
                        author="${CONFIG_project_author:-Author}"
                        url="${CONFIG_project_url:-}"
                        
                        sed -e "s|{{TITLE}}|$title|g" \
                            -e "s|{{AUTHOR}}|$author|g" \
                            -e "s|{{URL}}|$url|g" \
                            "$WORKSPACE_ROOT/common/frontmatter/title.tex" > "frontmatter/title.tex"
                    fi
                    ;;
                    
                preface|acknowledgments|introduction)
                    # Check if frontmatter file already exists
                    if [[ -f "frontmatter/${item}.tex" ]]; then
                        log "  → Frontmatter exists: $item (skipping)"
                    else
                        # Check for custom version first
                        custom_fm="$CUSTOM_DIR/frontmatter/${item}.tex"
                        if [[ -f "$custom_fm" ]]; then
                            log "  → Using custom $item"
                            ensure_dir "frontmatter"
                            cp "$custom_fm" "frontmatter/${item}.tex"
                        else
                            # Generate from template using generator script
                            if [[ -f "$WORKSPACE_ROOT/scripts/generator/frontmatter.sh" ]]; then
                                log "  → Generating $item from template"
                                bash "$WORKSPACE_ROOT/scripts/generator/frontmatter.sh" -t "$item" workspace.yml
                            else
                                warn "Frontmatter generator not found, skipping $item"
                            fi
                        fi
                    fi
                    ;;
            esac
        done
    fi
fi

# Update hyperref with metadata
{
    echo ""
    echo "% Metadata"
    echo "\\hypersetup{"
    echo "  pdftitle={${CONFIG_project_title:-Untitled}},"
    echo "  pdfauthor={${CONFIG_project_author:-Author}},"
    echo "  pdfsubject={${CONFIG_project_subject:-}},"
    echo "  pdfkeywords={${CONFIG_project_keywords:-}},"
    echo "  colorlinks=true,"
    
    if [[ "$PROJECT_CATEGORY" == "academic" ]]; then
        echo "  linkcolor=black,"
        echo "  citecolor=black,"
        echo "  urlcolor=blue"
    else
        echo "  linkcolor=accent,"
        echo "  citecolor=accent,"
        echo "  urlcolor=accent"
    fi
    
    echo "}"
} >> "$WORKSPACE_DIR/preset.tex"

# Generate version command
VERSION=$(get_version)
BUILD_DATE=$(get_build_date)

{
    echo ""
    echo "% Version information"
    echo "\\newcommand{\\ProjectVersion}{$VERSION}"
    echo "\\newcommand{\\BuildDate}{$BUILD_DATE}"
} >> "$WORKSPACE_DIR/preset.tex"

log "✓ Sync completed successfully!"
info ""
info "Generated files:"
info "  - $WORKSPACE_DIR/preset.tex (main preset)"
info "  - $WORKSPACE_DIR/components/ (synced components)"
info ""
info "Configuration:"
info "  - Version: $VERSION"
info "  - Build date: $BUILD_DATE"
info "  - Category: $PROJECT_CATEGORY"
info "  - Color scheme: $COLOR_SCHEME"
info "  - Override directory: $CUSTOM_DIR"
info ""
info "Ready to build! Run: make build"