#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

source "$SCRIPT_DIR/context.sh"
source "$SCRIPT_DIR/utils/logger.sh"
source "$SCRIPT_DIR/utils/utils.sh"
source "$SCRIPT_DIR/utils/gitinfo.sh"
source "$SCRIPT_DIR/parser.sh"
source "$SCRIPT_DIR/loader.sh"
source "$SCRIPT_DIR/checker.sh"
source "$SCRIPT_DIR/bootstrap.sh"

main() {
    bootstrap_paths
    bootstrap_defaults

    check_workspace_file || error "No workspace.yml found. Run: bash workspace/src/init.sh"

    load_config "$WORKSPACE_FILE"

    bootstrap_version
    derive_context

    log "Syncing workspace..."
    log "Type: $PROJECT_TYPE"
    log "Override dir: $OVERRIDE_DIR"

    setup_pxis_dir
    sync_components
    apply_colors
    generate_frontmatter
    update_metadata
    generate_version_commands

    success "Sync done."
    info ""
    info "  .pxis/preset.tex regenerated"
    info "  Run 'make build' or just 'make' to compile"
}

setup_pxis_dir() {
    ensure_dir ".pxis"
    ensure_dir ".pxis/components"
    ensure_dir ".pxis/components/commands"

    # Always regenerate preset.tex
    cat > ".pxis/preset.tex" <<EOF
% Auto-generated by workspace sync — do not edit directly
% Edit workspace.yml and run: make sync
% Generated: $(date)

EOF
}

sync_components() {
    COMPONENTS="${CONFIG_components:-}"

    if [[ -z "$COMPONENTS" ]]; then
        if [[ "$PROJECT_TYPE" == "book" ]]; then
            COMPONENTS="fonts math graphics tables hyperref colors layout titles pagestyles env index bibliography code boxes commands/base"
        else
            COMPONENTS="fonts math graphics tables hyperref colors layout bibliography code commands/base"
        fi
    fi

    log "Components:"
    for component in $COMPONENTS; do
        add_component "$component"
    done
}

add_component() {
    local component="$1"
    local override_dir="${OVERRIDE_DIR:-configs}"
    local override_path="${override_dir}/${component}.tex"
    local override_mode="${CONFIG_overrides_mode:-replace}"

    local target_dir=".pxis/components/$(dirname "$component")"
    ensure_dir "$target_dir"

    # If user has an override file for this component
    if [[ -f "$override_path" ]]; then
        if [[ "$override_mode" == "extend" ]]; then
            # extend: default component first, then user's additions
            log "  + extend: $component"
            local src=""
            if check_package_exists "$component"; then
                src="$WORKSPACE_ROOT/common/packages/${component}.tex"
            elif check_component_exists "$component"; then
                src="$WORKSPACE_ROOT/common/components/${component}.tex"
            fi
            {
                [[ -n "$src" ]] && cat "$src"
                echo ""
                echo "% --- user override (extend) ---"
                cat "$override_path"
            } > ".pxis/components/${component}.tex"
        else
            # replace mode: user file wins entirely
            log "  → override: $component"
            cp "$override_path" ".pxis/components/${component}.tex"
        fi
        echo "\\input{.pxis/components/${component}}" >> .pxis/preset.tex
        return
    fi

    # No override — use workspace default
    if check_package_exists "$component"; then
        log "  · package: $component"
        cp "$WORKSPACE_ROOT/common/packages/${component}.tex" ".pxis/components/${component}.tex"
        echo "\\input{.pxis/components/${component}}" >> .pxis/preset.tex
        return
    fi

    if check_component_exists "$component"; then
        log "  · component: $component"
        cp "$WORKSPACE_ROOT/common/components/${component}.tex" ".pxis/components/${component}.tex"
        echo "\\input{.pxis/components/${component}}" >> .pxis/preset.tex
        return
    fi

    # Check for extra user-defined component in override dir (no default exists)
    if [[ -f "${override_dir}/${component}.tex" ]]; then
        log "  + extra: $component (user-defined)"
        cp "${override_dir}/${component}.tex" ".pxis/components/${component}.tex"
        echo "\\input{.pxis/components/${component}}" >> .pxis/preset.tex
        return
    fi

    warn "Component not found: $component (skipping)"
}

apply_colors() {
    local scheme="${CONFIG_colors_scheme:-technical}"
    log "Color scheme: $scheme"

    # If user has configs/colors.tex, it's already handled by add_component
    # Just append applyColorScheme if not overridden
    local override_dir="${OVERRIDE_DIR:-configs}"
    if [[ ! -f "${override_dir}/colors.tex" ]]; then
        cat >> .pxis/preset.tex <<EOF

% Color scheme
\\applyColorScheme{$scheme}
EOF
    fi
}

generate_frontmatter() {
    [[ "$PROJECT_TYPE" != "book" ]] && return 0

    FRONTMATTER="${CONFIG_frontmatter:-}"
    [[ -z "$FRONTMATTER" ]] && return 0

    log "Frontmatter:"

    for item in $FRONTMATTER; do
        case "$item" in
            cover)     gen_cover ;;
            copyright) gen_copyright ;;
            title)     gen_title ;;
            preface|acknowledgments|introduction) gen_frontmatter_item "$item" ;;
        esac
    done
}

gen_cover() {
    local cover_type="${CONFIG_cover_type:-generated}"

    if [[ "$cover_type" == "generated" ]]; then
        # Only generate if not already written by user
        if [[ ! -f "frontmatter/cover.tex" ]]; then
            log "  · generating cover"
            bash "$WORKSPACE_ROOT/src/generator/cover.sh" "$WORKSPACE_FILE"
        else
            log "  · cover exists, skipping"
        fi
    fi
}

gen_copyright() {
    # Only generate if user hasn't written one
    if [[ ! -f "frontmatter/copyright.tex" ]]; then
        log "  · generating copyright"
        bash "$WORKSPACE_ROOT/src/generator/copyright.sh" "$WORKSPACE_FILE"
    else
        log "  · copyright exists, skipping"
    fi
}

gen_title() {
    if [[ ! -f "frontmatter/title.tex" ]]; then
        log "  · generating title"
        local override_dir="${OVERRIDE_DIR:-configs}"
        local custom="${override_dir}/frontmatter/title.tex"

        ensure_dir "frontmatter"

        if [[ -f "$custom" ]]; then
            cp "$custom" "frontmatter/title.tex"
        elif [[ -f "$WORKSPACE_ROOT/common/frontmatter/title.tex" ]]; then
            local title="${CONFIG_project_title:-Untitled}"
            local author="${CONFIG_project_author:-Author}"
            local url="${CONFIG_project_url:-}"
            sed -e "s|{{TITLE}}|$title|g" \
                -e "s|{{AUTHOR}}|$author|g" \
                -e "s|{{URL}}|$url|g" \
                "$WORKSPACE_ROOT/common/frontmatter/title.tex" > "frontmatter/title.tex"
        fi
    else
        log "  · title exists, skipping"
    fi
}

gen_frontmatter_item() {
    local item="$1"

    if [[ -f "frontmatter/${item}.tex" ]]; then
        log "  · ${item} exists, skipping"
        return
    fi

    ensure_dir "frontmatter"

    local override_dir="${OVERRIDE_DIR:-configs}"
    local custom="${override_dir}/frontmatter/${item}.tex"

    # User has a custom version in configs/frontmatter/
    if [[ -f "$custom" ]]; then
        log "  · ${item} from override"
        cp "$custom" "frontmatter/${item}.tex"
        return
    fi

    # Use workspace template (with placeholder substitution)
    local tmpl="$WORKSPACE_ROOT/template/books/frontmatter/${item}.tex"
    if [[ -f "$tmpl" ]]; then
        log "  · generating ${item}"
        local title="${CONFIG_project_title:-Untitled}"
        local author="${CONFIG_project_author:-Author}"
        local url="${CONFIG_project_url:-}"
        sed -e "s|{{TITLE}}|$title|g" \
            -e "s|{{AUTHOR}}|$author|g" \
            -e "s|{{URL}}|$url|g" \
            "$tmpl" > "frontmatter/${item}.tex"
        return
    fi

    warn "No template found for frontmatter: ${item} (skipping)"
}

update_metadata() {
    local link_color="accent"
    local cite_color="accent"
    local url_color="accent"

    cat >> .pxis/preset.tex <<EOF

% PDF metadata
\\hypersetup{
  pdftitle={${CONFIG_project_title:-Untitled}},
  pdfauthor={${CONFIG_project_author:-Author}},
  pdfsubject={${CONFIG_project_subject:-}},
  pdfkeywords={${CONFIG_project_keywords:-}},
  colorlinks=true,
  linkcolor=$link_color,
  citecolor=$cite_color,
  urlcolor=$url_color
}
EOF
}

generate_version_commands() {
    cat >> .pxis/preset.tex <<EOF

% Version
\\newcommand{\\ProjectVersion}{$VERSION}
\\newcommand{\\BuildDate}{$BUILD_DATE}
EOF
}

main "$@"