#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

source "$SCRIPT_DIR/context.sh"
source "$SCRIPT_DIR/utils/logger.sh"
source "$SCRIPT_DIR/utils/utils.sh"
source "$SCRIPT_DIR/utils/gitinfo.sh"
source "$SCRIPT_DIR/parser.sh"
source "$SCRIPT_DIR/loader.sh"
source "$SCRIPT_DIR/checker.sh"
source "$SCRIPT_DIR/bootstrap.sh"

main() {
    bootstrap_paths
    bootstrap_defaults
    
    check_workspace_file || error "No workspace.yml found. Run init.sh first."
    
    load_config "$WORKSPACE_FILE"
    
    bootstrap_version
    derive_context
    
    log "Syncing workspace components..."
    log "Project type: $PROJECT_TYPE"
    log "Category: $PROJECT_CATEGORY"
    log "Override directory: $OVERRIDE_DIR"
    
    setup_workspace_dir
    sync_components
    apply_color_scheme
    generate_frontmatter
    update_metadata
    generate_version_commands
    
    success "Sync completed successfully!"
    info ""
    info "Generated files:"
    info "  - .pxis/preset.tex (main preset)"
    info "  - .pxis/components/ (synced components)"
    info ""
    info "Configuration:"
    info "  - Version: $VERSION"
    info "  - Build date: $BUILD_DATE"
    info "  - Category: $PROJECT_CATEGORY"
    info ""
    info "Ready to build! Run: make"
}

setup_workspace_dir() {
    local workspace_dir=".pxis"
    
    ensure_dir "$workspace_dir"
    ensure_dir "$workspace_dir/components"
    ensure_dir "$workspace_dir/generated"
    
    rm -f "$workspace_dir/preset.tex"
    rm -rf "$workspace_dir/components"/*
    
    cat > "$workspace_dir/preset.tex" <<EOF
% Auto-generated by Papyrxis workspace sync
% DO NOT EDIT - This file is regenerated on each build
% Edit workspace.yml to configure components
% Generated: $(date)

EOF
}

sync_components() {
    COMPONENTS="${CONFIG_components:-}"
    
    if [[ -z "$COMPONENTS" ]]; then
        log "Using default component set for $PROJECT_CATEGORY $PROJECT_TYPE"
        
        if [[ "$PROJECT_TYPE" == "book" ]]; then
            COMPONENTS="fonts math graphics tables hyperref colors layout titles pagestyles env index bibliography code boxes commands/base"
        else
            COMPONENTS="fonts math graphics tables hyperref colors layout bibliography code commands/base"
        fi
    fi
    
    log "Adding components..."
    for component in $COMPONENTS; do
        add_component "$component"
    done
}

add_component() {
    local component="$1"
    local override_path="$OVERRIDE_DIR/${component}.tex"
    local component_file="${component}.tex"
    
    if [[ -f "$override_path" ]] && check_override_allowed "$component_file"; then
        log "  → Using override: $component"
        local target_dir=".pxis/components/$(dirname "$component")"
        ensure_dir "$target_dir"
        cp "$override_path" ".pxis/components/${component}.tex"
        echo "\\input{.pxis/components/${component}}" >> .pxis/preset.tex
        return
    fi
    
    if check_package_exists "$component"; then
        log "  → Adding package: $component"
        cp "$WORKSPACE_ROOT/common/packages/${component}.tex" ".pxis/components/${component}.tex"
        echo "\\input{.pxis/components/${component}}" >> .pxis/preset.tex
        return
    fi
    
    if check_component_exists "$component"; then
        log "  → Adding component: $component"
        local target_dir=".pxis/components/$(dirname "$component")"
        ensure_dir "$target_dir"
        cp "$WORKSPACE_ROOT/common/components/${component}.tex" ".pxis/components/${component}.tex"
        echo "\\input{.pxis/components/${component}}" >> .pxis/preset.tex
        return
    fi
    
    warn "Component not found: $component (skipping)"
}

apply_color_scheme() {
    COLOR_SCHEME="${CONFIG_colors_scheme:-$PROJECT_CATEGORY}"
    log "Applying color scheme: $COLOR_SCHEME"
    
    local custom_colors="$OVERRIDE_DIR/colors.tex"
    if [[ -f "$custom_colors" ]] && check_override_allowed "colors.tex"; then
        log "  → Using custom colors"
        return
    fi
    
    cat >> .pxis/preset.tex <<EOF

% Color scheme: $COLOR_SCHEME
\\applyColorScheme{$COLOR_SCHEME}
EOF
}

generate_frontmatter() {
    [[ "$PROJECT_TYPE" != "book" ]] && return 0
    
    FRONTMATTER="${CONFIG_frontmatter:-}"
    [[ -z "$FRONTMATTER" ]] && return 0
    
    log "Generating frontmatter..."
    
    for item in $FRONTMATTER; do
        case "$item" in
            cover)
                generate_cover
                ;;
            copyright)
                generate_copyright
                ;;
            title)
                generate_title
                ;;
            preface|acknowledgments|introduction)
                generate_frontmatter_item "$item"
                ;;
        esac
    done
}

generate_cover() {
    local cover_type="${CONFIG_cover_type:-generated}"
    
    if [[ "$cover_type" == "pdf" ]]; then
        local pdf_file="${CONFIG_cover_pdf_file:-cover.pdf}"
        if check_file_exists "$pdf_file"; then
            log "  → Using PDF cover: $pdf_file"
        else
            warn "PDF cover not found: $pdf_file"
        fi
    elif [[ "$cover_type" == "generated" ]]; then
        log "  → Generating cover page"
        bash "$WORKSPACE_ROOT/src/generator/cover.sh" "$WORKSPACE_FILE"
    fi
}

generate_copyright() {
    log "  → Generating copyright page"
    bash "$WORKSPACE_ROOT/src/generator/copyright.sh" "$WORKSPACE_FILE"
}

generate_title() {
    local custom_title="$OVERRIDE_DIR/frontmatter/title.tex"
    
    if [[ -f "$custom_title" ]] && check_override_allowed "frontmatter/title.tex"; then
        log "  → Using custom title page"
        ensure_dir "frontmatter"
        cp "$custom_title" "frontmatter/title.tex"
        return
    fi
    
    if check_file_exists "$WORKSPACE_ROOT/common/frontmatter/title.tex"; then
        log "  → Using default title page"
        ensure_dir "frontmatter"
        
        local title="${CONFIG_project_title:-Untitled}"
        local author="${CONFIG_project_author:-Author}"
        local url="${CONFIG_project_url:-}"
        
        sed -e "s|{{TITLE}}|$title|g" \
            -e "s|{{AUTHOR}}|$author|g" \
            -e "s|{{URL}}|$url|g" \
            "$WORKSPACE_ROOT/common/frontmatter/title.tex" > "frontmatter/title.tex"
    fi
}

generate_frontmatter_item() {
    local item="$1"
    
    if check_file_exists "frontmatter/${item}.tex"; then
        log "  → Frontmatter exists: $item (skipping)"
        return
    fi
    
    local custom_fm="$OVERRIDE_DIR/frontmatter/${item}.tex"
    if [[ -f "$custom_fm" ]]; then
        log "  → Using custom $item"
        ensure_dir "frontmatter"
        cp "$custom_fm" "frontmatter/${item}.tex"
        return
    fi
    
    if check_file_exists "$WORKSPACE_ROOT/src/generator/frontmatter.sh"; then
        log "  → Generating $item from template"
        bash "$WORKSPACE_ROOT/src/generator/frontmatter.sh" -t "$item" "$WORKSPACE_FILE"
    else
        warn "Frontmatter generator not found, skipping $item"
    fi
}

update_metadata() {
    local link_color="accent"
    local cite_color="accent"
    local url_color="accent"
    
    if [[ "$PROJECT_CATEGORY" == "academic" ]]; then
        link_color="black"
        cite_color="black"
        url_color="blue"
    fi
    
    cat >> .pxis/preset.tex <<EOF

% Metadata
\\hypersetup{
  pdftitle={${CONFIG_project_title:-Untitled}},
  pdfauthor={${CONFIG_project_author:-Author}},
  pdfsubject={${CONFIG_project_subject:-}},
  pdfkeywords={${CONFIG_project_keywords:-}},
  colorlinks=true,
  linkcolor=$link_color,
  citecolor=$cite_color,
  urlcolor=$url_color
}
EOF
}

generate_version_commands() {
    cat >> .pxis/preset.tex <<EOF

% Version information
\\newcommand{\\ProjectVersion}{$VERSION}
\\newcommand{\\BuildDate}{$BUILD_DATE}
EOF
}

main "$@"